### ISSUE TITLE
Search not working in components

### ISSUE THREAD

**Issue by Vaibhav-npc** [notum-cz/strapi-plugin-location#27]
Although the geo fields are getting created in the tables for components with location custom field, none of the below approaches are able to search if the location field is inside the component. Below is the sample that I tried to pass as parameter. address is the component name and loc is location custom field.

$location[address][loc]
$location[address.loc]

**Comment by omikulcik** [comment]
Thank you for reporting this issue. We will strive to fix this by the next release.

**Comment by omikulcik** [comment]
Closed by #47
