### ISSUE TITLE
No able to see the location custom type

### ISSUE THREAD

**Issue by qmidy** [notum-cz/strapi-plugin-location#41]
## Bug report
Hi, 

Thanks for your work ! 

### Describe the bug

After installing the plugin : 
![image](https://github.com/notum-cz/strapi-plugin-location/assets/5627607/a260796a-1e89-4ef9-a999-53fd83f956d2)

![image](https://github.com/notum-cz/strapi-plugin-location/assets/5627607/801f779d-85a5-48ea-950f-8cd86e4a0a56)

It seems to be well installed, but i can't see any location custom type in the content manager :

![image](https://github.com/notum-cz/strapi-plugin-location/assets/5627607/d4680337-471b-434b-a433-29124667e64d)

### Steps to reproduce the behavior

1. Generate new empty strapi project on PostgreSQL with PostGIS installed
2. Add the plugin 

![image](https://github.com/notum-cz/strapi-plugin-location/assets/5627607/63deb076-6f09-4910-8c98-8a4704c19f63)

3. I'm not able to use the custom type
![image](https://github.com/notum-cz/strapi-plugin-location/assets/5627607/d4680337-471b-434b-a433-29124667e64d)

### Expected behavior

be able to use the custom type

### System

- Node.js version: v16.18.1
- NPM version: 8.19.2
- Strapi version: 4.12.4
- Database: postgreSQL
- Operating system: Windows 10
- Location Plugin : 1.0.2

### Additional context

I also try to modify the json directly by adding the custom type on a field named location but the create page was loading indefinitely
and i can't see the content manager which showed a blank page. 

I'm ok to check the code, if you can tell me where i must take a look to eventually fix it (i already put a lot of console.log in the node_module)

**Comment by qmidy** [comment]
Fixed after updating to 4.13.3... Shame on me :(

**Comment by omikulcik** [comment]
Hi @qmidy, no worries. Happy that you have solved it :) I guess this issue is to be closed then.
