### ISSUE TITLE
'All changes made will be lost' warning upon exiting unedited collection item

### ISSUE THREAD

**Issue by claudiobgit** [notum-cz/strapi-plugin-location#51]
### Describe the bug

When exiting an item that features the plugin custom fields, the user is warned about data loss and forced to click 'Save', even if nothing was updated.

### Steps to reproduce the behavior

1. In the Content Manager go to a collection where you use the lat/lon custom field
2. Click on a collection item an open it
3. Do not edit anything
4. Click the Back link at the top of the page
5. See error

### Expected behavior

Normally going back to the items list of the collection as no content was updated.

**Comment by omikulcik** [comment]
@claudiobgit Thank you for reporting this. I will check whether this could be fixed.
