### ISSUE TITLE
Errors in Plugin Build

### ISSUE THREAD

**Issue by Ademboussetha** [notum-cz/strapi-plugin-location#79]
**Description:**

When attempting to build the Strapi plugin "strapi-plugin-location" using the command `npm run build`, I encounter TypeScript errors that indicate 'strapi.db' is possibly undefined.

**Environment:**
- Node.js version: Tried 16 and 19.
- npm version: 9.2.0
- TypeScript version: 5.2.2

**Steps to Reproduce:**
1. Clone the repository.
2. Install dependencies using `npm install`.
3. Run the build command using `npm run build`.
4. Observe the TypeScript errors.

**Error Messages:**
server/bootstrap.ts:13:14 - error TS18048: 'strapi.db' is possibly 'undefined'. const db = strapi.db.connection;

**Troubleshooting Steps Taken:**
- I tried many ways to solve it by changing the node version and deleting the node_modules folder + package-lock.json everytime and run `npm install` but still the same issue.

![image](https://github.com/notum-cz/strapi-plugin-location/assets/55892173/9b701979-373d-41fa-8884-67f859906c38)

Please let me know if you need any further assistance or have any specific details to add to the issue description.

**Comment by omikulcik** [comment]
Hey @Ademboussetha, I have uploaded a fix. Strapi must have changed their typings so we will have to settle for ts-expect-errors now...
